/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apif0a60b76",
            "endpoint": "https://2bc6cgnu0f.execute-api.ap-northeast-1.amazonaws.com/amplify",
            "region": "ap-northeast-1"
        }
    ]
};


export default awsmobile;
